import React from "react";
import '../index.css'
const About = () => {
  return (
    <div className="h-body">
      <h1 className="card-title">About Us</h1>
      <p className="card-text">
        Used API=https://randomuser.me/api/?nat=us&results=18&page=1 <br/><br/>
        This Site fetches and displays 18 random users generated by the above API.
        Developed & Designed by Raphul.
      </p>
    </div>
  );
};
  
export default About;